title: "Maciej Buczak"
description: "Risk Management & Research"
theme: jekyll-theme-slate
permalink: /:title/
collections:
 publications:
   output: true
   permalink: /publications/:title/
head:
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css
