title: "Strona Macieja Buczaka"
description: "Blog i portfolio"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 5
paginate_path: "/page:num/"

# Ustawienia autora
author:
  name: "Maciej Buczak"
  avatar: "/assets/images/profile.png"
  bio: "Ekspert w zarządzaniu ryzykiem i statystyce."
  location: "Polska"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/MaciejBuczak"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"

# Menu nawigacyjne
header_pages:
  - about.md
  - blog.md

# Wygląd strony
layout: home
entries_layout: grid
show_excerpts: true
