# _config.yml
title: "Maciej Buczak"
description: "Risk Management & Research"
theme: jekyll-theme-slate
permalink: /:title/
collections:
  publications:
    output: true
    permalink: /publications/:title/
include: [_includes]
